In [45]:
from bs4 import BeautifulSoup

html_code = """
<body>
<div class="headerwrapperdiv">
<div class="pageheaderdiv1">
<a href="#main_content" onMouseover="window.status='Go to Main Content'; return true" onMouseout="window.status=''; return true" OnFocus="window.status='Go to Main Content'; return true" onBlur="window.status=''; return true" class="skiplinks">Go to Main Content</a>
<h1>  </h1></DIV><div class="headerlinksdiv">
<SPAN class="pageheaderlinks2">
<map name="Module_Navigation_Links_H" title="Module Navigation Links">
<p>
<a href="#skip_Module_Navigation_Links_H" onMouseover="window.status='Skip Module Navigation Links'; return true" onMouseout="window.status=''; return true" onFocus="window.status='Skip Module Navigation Links'; return true" onBlur="window.status=''; return true"  class="skiplinks">Skip Module Navigation Links</a>
<table  CLASS="plaintable" SUMMARY="This is main table for displaying Tab Items."
                          WIDTH="100%" cellSpacing=0 cellPadding=0 border=0>
<tr>
<TD CLASS="pldefault">
<table  CLASS="plaintable" SUMMARY="This table displays Tab Items."
                 cellSpacing=0 cellPadding=0 border=0>
<tr>
<td class="taboff" height=22>
<a href="/BPROD/twbkwbis.P_GenMenu?name=bmenu.P_GenMnu" onMouseover="window.status='New Personal Information'; return true" onMouseout="window.status=''; return true" onFocus="window.status='New Personal Information'; return true" onBlur="window.status=''; return true" >Personal Information</a>
</TD>
<TD class="bgtaboff" height=22 vAlign="top" align="right">
<img src="/wtlgifs/web_tab_corner_right.gif" alt="Tab Corner Right" CLASS="headerImg" TITLE="Tab Corner Right"  NAME="web_tab_corner_right" HSPACE=0 VSPACE=0 BORDER=0 HEIGHT=20 WIDTH=8 />
</TD>
<td class="tabon"  height=22>
<a href="/BPROD/twbkwbis.P_GenMenu?name=bmenu.P_FacMainMnu" onMouseover="window.status='Faculty Services'; return true" onMouseout="window.status=''; return true" onFocus="window.status='Faculty Services'; return true" onBlur="window.status=''; return true" >Faculty Services</a>
</TD>
<TD class="bgtabon"  height=22 vAlign="top" align="right">
<img src="/wtlgifs/web_tab_corner_right.gif" alt="Tab Corner Right" CLASS="headerImg" TITLE="Tab Corner Right"  NAME="web_tab_corner_right" HSPACE=0 VSPACE=0 BORDER=0 HEIGHT=20 WIDTH=8 />
</TD>
</tr>
</table>
</TD>
</tr>
<tr>
<TD class="bgtabon" width="100%" colSpan=2><img src="/wtlgifs/web_transparent.gif" alt="Transparent Image" CLASS="headerImg" TITLE="Transparent Image"  NAME="web_transparent" HSPACE=0 VSPACE=0 BORDER=0 HEIGHT=3 WIDTH=10 /></TD></tr></table>
</map>
</SPAN>
<a name="skip_Module_Navigation_Links_H"></a>
</DIV>
<table  CLASS="plaintable" SUMMARY="This table displays Menu Items and Banner Search textbox." WIDTH="100%">
<tr>
<TD CLASS="pldefault">
<div class="headerlinksdiv2">
<form action="/BPROD/twbksrch.P_ShowResults" method="post">
Search
<SPAN class="fieldlabeltextinvisible"><LABEL for=keyword_in_id><SPAN class="fieldlabeltext">Search</SPAN></LABEL></SPAN>
<input type="text" name="KEYWRD_IN" size="20" maxlength="65" ID="keyword_in_id" />
<input type="submit" value="Go" />
</form>
</div>
</TD>
<TD CLASS="pldefault"><p class="rightaligntext" /p>
<div style = "text-align:right">
<SPAN class="pageheaderlinks">
<a href="/BPROD/twbkwbis.P_GenMenu?name=bmenu.P_FacStuMnu"  class="submenulinktext2" id="ssbbackurl">MENU</a>
|
<a href="/BPROD/twbksite.P_DispSiteMap?menu_name_in=bmenu.P_MainMnu&amp;depth_in=2&amp;columns_in=3" accesskey="2" class="submenulinktext2">SITE MAP</a>
|
<a href="/wtlhelp/twbhhelp.htm" accesskey="H" onClick="popup = window.open('/wtlhelp/twbhhelp.htm', 'PopupPage','height=500,width=450,scrollbars=yes,resizable=yes'); return false" target="_blank" onMouseOver="window.status='';  return true" onMouseOut="window.status=''; return true"onFocus="window.status='';  return true" onBlur="window.status=''; return true"  class="submenulinktext2">HELP</a>
|
<a href="twbkwbis.P_Logout" accesskey="3" class="submenulinktext2">EXIT</a>
</span>
</div>
</TD>
</tr>
</table>
</DIV>
<div class="pagetitlediv">
<table  CLASS="plaintable" SUMMARY="This table displays title and static header displays." WIDTH="100%">
<tr>
<TD CLASS="pldefault">
<h2>Student Unofficial Academic Transcript</h2>
</TD>
<TD CLASS="pldefault">
&nbsp;
</TD>
<TD CLASS="pldefault"><p class="rightaligntext" /p>
<div class="staticheaders">
713014589 Hyun Bin Kang<br>
Mar 28, 2024 12:41 pm<br>
</div>
</TD>
</tr>
<tr>
<TD class="bg3" width="100%" colSpan=3><img src="/wtlgifs/web_transparent.gif" alt="Transparent Image" CLASS="headerImg" TITLE="Transparent Image"  NAME="web_transparent" HSPACE=0 VSPACE=0 BORDER=0 HEIGHT=3 WIDTH=10 /></TD>
</tr>
</table>
<a name="main_content"></a>
</DIV>
<div class="pagebodydiv">
<!--  ** END OF twbkwbis.P_OpenDoc **  -->
<div class="infotextdiv"><table  CLASS="infotexttable" SUMMARY="This layout table contains information that may be helpful in understanding the content and functionality of this page.  It could be a brief set of instructions, a description of error messages, or other special information."><tr><td CLASS="indefault">&nbsp;</td><td CLASS="indefault"><SPAN class="infotext"> <b>An 'E' in the R (Repeated course) column indicates a course is excluded from the GPA; an 'I' indicates that the course is included in the GPA.</b></SPAN></td></tr></table></DIV><p><div class="infotextdiv"><table  CLASS="infotexttable" SUMMARY="This layout table contains information that may be helpful in understanding the content and functionality of this page.  It could be a brief set of instructions, a description of error messages, or other special information."><tr><td CLASS="indefault">&nbsp;</td><td CLASS="indefault"><SPAN class="infotext">Hint: Print the web transcript in landscape orientation for best effect.</SPAN></td></tr></table><p></DIV>
<table  CLASS="plaintable" summary="This layout table holds message information">
<tr>
<TD CLASS="pldefault">
&nbsp;
</TD>
<TD CLASS="pldefault">
Information for <a href="/BPROD/bwlkosad.P_FacSelectAtypView" name="Student Address" onMouseOver="window.status='Student Address';  return true" onFocus="window.status='Student Address';  return true" onMouseOut="window.status='';  return true"onBlur="window.status='';  return true">John Snow</a>
<br />
</TD>
</tr>
</table>
<a name="top">
</A>
<a href="#insti_credit">Institution Credit</a>
&nbsp&nbsp
<a href="#trans_totals">Transcript Totals</a>
&nbsp&nbsp
<a href="#crses_progress">Courses in Progress</a>
<p class="whitespace1">
<table  CLASS="datadisplaytable" SUMMARY="This table will display the
                                   user's Academic History in the following
                                   sections:  Degree Information, Transfer
                                   Credit By Institution, Institution
                                   Credit, Transcript Totals ,
                                   Courses In Progress." WIDTH="80%"><caption class="captiontext">Transcript Data</caption>
<tr>
<th colspan="12" CLASS="ddtitle" scope="colgroup" >STUDENT INFORMATION</th>
</tr>
<tr>
<th colspan="2" CLASS="ddlabel" scope="row" >Name :</th>
<td colspan="10" CLASS="dddefault">John Snow</td>
</tr>
<tr>
<th colspan="2" CLASS="ddlabel" scope="row" >Birth Date:</th>
<td colspan="10" CLASS="dddefault">Mar 15, 1813</td>
</tr>
<tr>
<th colspan="6" CLASS="ddtitle" scope="colgroup" >Curriculum Information</th>
</tr>
<tr>
<th colspan="6" CLASS="ddlabel" scope="row" >Current Program</th>
</tr>
<tr>
<th colspan="3" CLASS="ddlabel" scope="row" >College:</th>
<td colspan="3" CLASS="dddefault">Arts & Sciences</td>
</tr>
<tr>
<th colspan="3" CLASS="ddlabel" scope="row" >Major and Department:</th>
<td colspan="3" CLASS="dddefault">Data Science, Statistics</td>
</tr>
<tr>
<td colspan="12" CLASS="ddseparator">&nbsp;</td>
</tr>
<tr>
<td colspan="12" CLASS="ddseparator">***Transcript type:WEB is NOT Official ***</td>
</tr>
<tr>
<td colspan="12" CLASS="ddseparator">&nbsp;</td>
</tr>
<tr>
<th colspan="12" CLASS="ddtitle" scope="colgroup" >DEGREES AWARDED</th>
</tr>
<tr>
<th CLASS="ddlabel" scope="row" >Hold no slip:</th>
<td colspan="3" CLASS="dddefault">Master of Science</td>
<th colspan="2" CLASS="ddlabel" scope="row" >Degree Date:</th>
<td colspan="6" CLASS="dddefault">&nbsp;</td>
</tr>
<tr>
<th colspan="6" CLASS="ddtitle" scope="colgroup" >Curriculum Information</th>
</tr>
<tr>
<th colspan="12" CLASS="ddlabel" scope="row" >Primary Degree</th>
</tr>
<tr>
<th colspan="4" CLASS="ddlabel" scope="row" >Major:</th>
<td colspan="8" CLASS="dddefault">Data Science</td>
</tr>
<tr>
<td colspan="12" CLASS="ddseparator">&nbsp;</td>
</tr>
<tr>
<td colspan="12" CLASS="ddseparator">&nbsp;</td>
</tr>
<tr>
<th colspan="12" CLASS="ddtitle" scope="colgroup" >INSTITUTION CREDIT&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href="#top" ALT="TOP" >-Top-</a><a name="insti_credit"></A></th>
</tr>
<tr>
<th colspan="12" CLASS="ddlabel" scope="row" ><SPAN class="fieldOrangetextbold">Term: Spring 2023 </SPAN></th>
</tr>
<tr>
<th colspan="4" CLASS="ddlabel" scope="row" >Academic Standing:</th>
<td colspan="7" CLASS="dddefault">Good Standing</td>
</tr>
<tr>
<th CLASS="ddheader" scope="col" >Subject</th>
<th CLASS="ddheader" scope="col" >Course</th>
<th CLASS="ddheader" scope="col" >Level</th>
<th colspan="5" CLASS="ddheader" scope="col" >Title</th>
<th CLASS="ddheader" scope="col" >Grade</th>
<th CLASS="ddheader" scope="col" >Credit Hours</th>
<th CLASS="ddheader" scope="col" >Quality Points</th>
<th CLASS="ddheader" scope="col" ><ABBR title = "Repeat Status">R</ABBR></th>
</tr>
<tr>
<td CLASS="dddefault">CS</td>
<td CLASS="dddefault">5610</td>
<td CLASS="dddefault">GR</td>
<td colspan="5" CLASS="dddefault">Advanced R for Data Science</td>
<td CLASS="dddefault">B</td>
<td CLASS="dddefault"><p class="rightaligntext">        4.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             12.00</p></td>
<td CLASS="dddefault">&nbsp;</td>
<td CLASS="dddead">&nbsp;</td>
</tr>
<tr>
<td CLASS="dddefault">STAT</td>
<td CLASS="dddefault">5860</td>
<td CLASS="dddefault">GR</td>
<td colspan="5" CLASS="dddefault">Computer Based Data Analysis</td>
<td CLASS="dddefault">BA</td>
<td CLASS="dddefault"><p class="rightaligntext">        3.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             10.50</p></td>
<td CLASS="dddefault">&nbsp;</td>
<td CLASS="dddead">&nbsp;</td>
</tr>
<tr>
<th colspan="12" CLASS="ddtitle" scope="colgroup" >Term Totals (Graduate)</th>
</tr>
<tr>
<td colspan="5" CLASS="dddead">&nbsp;</td>
<th CLASS="ddheader" scope="col" >Attempt Hours</th>
<th CLASS="ddheader" scope="col" >Passed Hours</th>
<th CLASS="ddheader" scope="col" >Earned Hours</th>
<th CLASS="ddheader" scope="col" >GPA Hours</th>
<th CLASS="ddheader" scope="col" >Quality Points</th>
<th colspan="2" CLASS="ddheader" scope="col" >GPA</th>
</tr>
<tr>
<th colspan="5" CLASS="ddlabel" scope="row" >Current Term:</th>
<td CLASS="dddefault"><p class="rightaligntext">        7.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        7.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        7.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        7.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             22.50</p></td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">                     3.21</p></td>
</tr>
<tr>
<th colspan="5" CLASS="ddlabel" scope="row" >Cumulative:</th>
<td CLASS="dddefault"><p class="rightaligntext">        7.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        7.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        7.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        7.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             22.50</p></td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">                     3.21</p></td>
</tr>
<tr>
<td colspan="12" CLASS="ddseparator">&nbsp;</td>
</tr>
<tr>
<td colspan="4" CLASS="ddseparator"><div class="infotextdiv"><table  CLASS="infotexttable" SUMMARY="This layout table contains information that may be helpful in understanding the content and functionality of this page.  It could be a brief set of instructions, a description of error messages, or other special information."><tr><td CLASS="indefault"><SPAN class="infotext"> Western Michigan University Unofficial Transcript</SPAN></td></tr></table><p></DIV></td>
</tr>
<tr>
<th colspan="12" CLASS="ddlabel" scope="row" ><SPAN class="fieldOrangetextbold">Term: SummerI 2023</SPAN></th>
</tr>
<tr>
<th colspan="4" CLASS="ddlabel" scope="row" >Academic Standing:</th>
<td colspan="7" CLASS="dddefault">Good Standing</td>
</tr>
<tr>
<th CLASS="ddheader" scope="col" >Subject</th>
<th CLASS="ddheader" scope="col" >Course</th>
<th CLASS="ddheader" scope="col" >Level</th>
<th colspan="5" CLASS="ddheader" scope="col" >Title</th>
<th CLASS="ddheader" scope="col" >Grade</th>
<th CLASS="ddheader" scope="col" >Credit Hours</th>
<th CLASS="ddheader" scope="col" >Quality Points</th>
<th CLASS="ddheader" scope="col" ><ABBR title = "Repeat Status">R</ABBR></th>
</tr>
<tr>
<td CLASS="dddefault">STAT</td>
<td CLASS="dddefault">5630</td>
<td CLASS="dddefault">GR</td>
<td colspan="5" CLASS="dddefault">Sample Survey Methods</td>
<td CLASS="dddefault">A</td>
<td CLASS="dddefault"><p class="rightaligntext">        3.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             12.00</p></td>
<td CLASS="dddefault">&nbsp;</td>
<td CLASS="dddead">&nbsp;</td>
</tr>
<tr>
<th colspan="12" CLASS="ddtitle" scope="colgroup" >Term Totals (Graduate)</th>
</tr>
<tr>
<td colspan="5" CLASS="dddead">&nbsp;</td>
<th CLASS="ddheader" scope="col" >Attempt Hours</th>
<th CLASS="ddheader" scope="col" >Passed Hours</th>
<th CLASS="ddheader" scope="col" >Earned Hours</th>
<th CLASS="ddheader" scope="col" >GPA Hours</th>
<th CLASS="ddheader" scope="col" >Quality Points</th>
<th colspan="2" CLASS="ddheader" scope="col" >GPA</th>
</tr>
<tr>
<th colspan="5" CLASS="ddlabel" scope="row" >Current Term:</th>
<td CLASS="dddefault"><p class="rightaligntext">        3.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        3.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        3.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        3.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             12.00</p></td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">                     4.00</p></td>
</tr>
<tr>
<th colspan="5" CLASS="ddlabel" scope="row" >Cumulative:</th>
<td CLASS="dddefault"><p class="rightaligntext">       10.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       10.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       10.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       10.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             34.50</p></td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">                     3.45</p></td>
</tr>
<tr>
<td colspan="12" CLASS="ddseparator">&nbsp;</td>
</tr>
<tr>
<td colspan="4" CLASS="ddseparator"><div class="infotextdiv"><table  CLASS="infotexttable" SUMMARY="This layout table contains information that may be helpful in understanding the content and functionality of this page.  It could be a brief set of instructions, a description of error messages, or other special information."><tr><td CLASS="indefault"><SPAN class="infotext"> Western Michigan University Unofficial Transcript</SPAN></td></tr></table><p></DIV></td>
</tr>
<tr>
<th colspan="12" CLASS="ddlabel" scope="row" ><SPAN class="fieldOrangetextbold">Term: Fall 2023   </SPAN></th>
</tr>
<tr>
<th colspan="4" CLASS="ddlabel" scope="row" >Academic Standing:</th>
<td colspan="7" CLASS="dddefault">Good Standing</td>
</tr>
<tr>
<th CLASS="ddheader" scope="col" >Subject</th>
<th CLASS="ddheader" scope="col" >Course</th>
<th CLASS="ddheader" scope="col" >Level</th>
<th colspan="5" CLASS="ddheader" scope="col" >Title</th>
<th CLASS="ddheader" scope="col" >Grade</th>
<th CLASS="ddheader" scope="col" >Credit Hours</th>
<th CLASS="ddheader" scope="col" >Quality Points</th>
<th CLASS="ddheader" scope="col" ><ABBR title = "Repeat Status">R</ABBR></th>
</tr>
<tr>
<td CLASS="dddefault">CS</td>
<td CLASS="dddefault">5430</td>
<td CLASS="dddefault">GR</td>
<td colspan="5" CLASS="dddefault">Database Systems</td>
<td UPDATE Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions - Please note that updating to Notebook 7 might break some of your extensions.
Jupyter Notebook
Master's Project - Transcript Example1
Last Checkpoint: 20 minutes ago
(autosaved)
Current Kernel Logo
Python 3 (ipykernel) 
File
Edit
View
Insert
Cell
Kernel
Widgets
Help

Code
CLASS="dddefault">B</td>
<td CLASS="dddefault"><p class="rightaligntext">        3.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">              9.00</p></td>
<td CLASS="dddefault">&nbsp;</td>
<td CLASS="dddead">&nbsp;</td>
</tr>
<tr>
<td CLASS="dddefault">STAT</td>
<td CLASS="dddefault">5870</td>
<td CLASS="dddefault">GR</td>
<td colspan="5" CLASS="dddefault">Big Data Analysis Using Python</td>
<td CLASS="dddefault">A</td>
<td CLASS="dddefault"><p class="rightaligntext">        3.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             12.00</p></td>
<td CLASS="dddefault">&nbsp;</td>
<td CLASS="dddead">&nbsp;</td>
</tr>
<tr>
<td CLASS="dddefault">STAT</td>
<td CLASS="dddefault">6620</td>
<td CLASS="dddefault">GR</td>
<td colspan="5" CLASS="dddefault">Applied Linear Models</td>
<td CLASS="dddefault">B</td>
<td CLASS="dddefault"><p class="rightaligntext">        3.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">              9.00</p></td>
<td CLASS="dddefault">&nbsp;</td>
<td CLASS="dddead">&nbsp;</td>
</tr>
<tr>
<th colspan="12" CLASS="ddtitle" scope="colgroup" >Term Totals (Graduate)</th>
</tr>
<tr>
<td colspan="5" CLASS="dddead">&nbsp;</td>
<th CLASS="ddheader" scope="col" >Attempt Hours</th>
<th CLASS="ddheader" scope="col" >Passed Hours</th>
<th CLASS="ddheader" scope="col" >Earned Hours</th>
<th CLASS="ddheader" scope="col" >GPA Hours</th>
<th CLASS="ddheader" scope="col" >Quality Points</th>
<th colspan="2" CLASS="ddheader" scope="col" >GPA</th>
</tr>
<tr>
<th colspan="5" CLASS="ddlabel" scope="row" >Current Term:</th>
<td CLASS="dddefault"><p class="rightaligntext">        9.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        9.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        9.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        9.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             30.00</p></td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">                     3.33</p></td>
</tr>
<tr>
<th colspan="5" CLASS="ddlabel" scope="row" >Cumulative:</th>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             66.50</p></td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">                     3.39</p></td>
</tr>
<tr>
<td colspan="11" CLASS="ddseparator">&nbsp;</td>
</tr>
<tr>
<td colspan="4" CLASS="ddseparator"><div class="infotextdiv"><table  CLASS="infotexttable" SUMMARY="This layout table contains information that may be helpful in understanding the content and functionality of this page.  It could be a brief set of instructions, a description of error messages, or other special information."><tr><td CLASS="indefault"><SPAN class="infotext"> Western Michigan University Unofficial Transcript</SPAN></td></tr></table><p></DIV></td>
</tr>
<tr>
<th colspan="11" CLASS="ddtitle" scope="colgroup" >TRANSCRIPT TOTALS (GRADUATE)&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href="#top" ALT="TOP" >-Top-</a><a name="trans_totals"></A></th>
</tr>
<tr>
<td colspan="4" CLASS="dddead">&nbsp;</td>
<th CLASS="ddheader" scope="col" >Attempt Hours</th>
<th CLASS="ddheader" scope="col" >Passed Hours</th>
<th CLASS="ddheader" scope="col" >Earned Hours</th>
<th CLASS="ddheader" scope="col" >GPA Hours</th>
<th CLASS="ddheader" scope="col" >Quality Points</th>
<th colspan="2" CLASS="ddheader" scope="col" >GPA</th>
</tr>
<tr>
<th colspan="4" CLASS="ddlabel" scope="row" >Total Institution:</th>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             66.50</p></td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">                     3.50</p></td>
</tr>
<tr>
<th colspan="4" CLASS="ddlabel" scope="row" >Total Transfer:</th>
<td CLASS="dddefault"><p class="rightaligntext">        0.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        0.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        0.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">        0.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">              0.00</p></td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">                     0.00</p></td>
</tr>
<tr>
<th colspan="4" CLASS="ddlabel" scope="row" >Overall:</th>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">       19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             19.000</p></td>
<td CLASS="dddefault"><p class="rightaligntext">             66.50</p></td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">                     3.50</p></td>
</tr>
<tr>
<td colspan="11" CLASS="ddseparator">&nbsp;</td>
</tr>
<tr>
<td colspan="4" CLASS="ddseparator"><div class="infotextdiv"><table  CLASS="infotexttable" SUMMARY="This layout table contains information that may be helpful in understanding the content and functionality of this page.  It could be a brief set of instructions, a description of error messages, or other special information."><tr><td CLASS="indefault"><SPAN class="infotext"> Western Michigan University Unofficial Transcript</SPAN></td></tr></table><p></DIV></td>
</tr>
<tr>
<th colspan="11" CLASS="ddtitle" scope="colgroup" >COURSES IN PROGRESS   &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href="#top" ALT="TOP" >-Top-</a><a name="crses_progress"></A></th>
</tr>
<tr>
<th colspan="11" CLASS="ddlabel" scope="row" ><SPAN class="fieldOrangetextbold">Term: Spring 2024 </SPAN></th>
</tr>
<tr>
<th CLASS="ddheader" scope="col" >Subject</th>
<th CLASS="ddheader" scope="col" >Course</th>
<th CLASS="ddheader" scope="col" >Level</th>
<th colspan="6" CLASS="ddheader" scope="col" >Title</th>
<th colspan="2" CLASS="ddheader" scope="col" >Credit Hours</th>
</tr>
<tr>
<tr>
<td CLASS="dddefault">CS</td>
<td CLASS="dddefault">5821</td>
<td CLASS="dddefault">GR</td>
<td colspan="6" CLASS="dddefault">Machine Learning</td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">    3.000</p></td>
</tr>
<tr>
<td CLASS="dddefault">STAT</td>
<td CLASS="dddefault">6640</td>
<td CLASS="dddefault">GR</td>
<td colspan="6" CLASS="dddefault">Applied Mixed Models</td>
<td colspan="2" CLASS="dddefault"><p class="rightaligntext">    3.000</p></td>
</tr>
<tr>
<td colspan="11" CLASS="ddseparator">&nbsp;</td>
</tr>
<tr>
<td colspan="4" CLASS="ddseparator"><div class="infotextdiv"><table  CLASS="infotexttable" SUMMARY="This layout table contains information that may be helpful in understanding the content and functionality of this page.  It could be a brief set of instructions, a description of error messages, or other special information."><tr><td CLASS="indefault"><SPAN class="infotext"> Western Michigan University Unofficial Transcript</SPAN></td></tr></table><p></DIV></td>
</tr>
</table>

<!--  ** START OF twbkwbis.P_CloseDoc **  -->
<table  CLASS="plaintable" SUMMARY="This is table displays line separator at end of the page." WIDTH="100%" cellSpacing=0 cellPadding=0 border=0><tr><TD class="bgtabon" width="100%" colSpan=2><img src="/wtlgifs/web_transparent.gif" alt="Transparent Image" CLASS="headerImg" TITLE="Transparent Image"  NAME="web_transparent" HSPACE=0 VSPACE=0 BORDER=0 HEIGHT=3 WIDTH=10 /></TD></tr></table>
<a href="#top" onMouseover="window.status='Skip to top of page'; return true" onMouseout="window.status=''; return true" OnFocus="window.status='Skip to top of page'; return true" onBlur="window.status=''; return true" class="skiplinks">Skip to top of page</a>
</DIV>
<div class="footerbeforediv">

</DIV>
<div class="footerlinksdiv">
<SPAN class="pagefooterlinks">
<map name="Student_Unofficial_Academic_Transcript_Links_F" title="Student Unofficial Academic Transcript Links">
<p>
<a href="#skip_Student_Unofficial_Academic_Transcript_Links_F" onMouseover="window.status='Skip Student Unofficial Academic Transcript Links'; return true" onMouseout="window.status=''; return true" onFocus="window.status='Skip Student Unofficial Academic Transcript Links'; return true" onBlur="window.status=''; return true"  class="skiplinks">Skip Student Unofficial Academic Transcript Links</a>
<P>[ <a href="/BPROD/twbkwbis.P_GenMenu?name=bwlkoids.P_FacIDSel">ID Selection</a>
 | <a href="/BPROD/twbkwbis.P_GenMenu?name=bwlktest.P_FacDispTest">Student Test Scores</a>
 | <a href="/BPROD/twbkwbis.P_GenMenu?name=bmenu.P_FacAdvrMnu">Return to Advisor menu</a>
 | <a href="/BPROD/twbkwbis.P_GenMenu?name=bmenu.P_FacMainMnu">Return to Faculty & Advisors Services menu</a>
 ]
</map>
</SPAN>
<a name="skip_Student_Unofficial_Academic_Transcript_Links_F"></a>
</DIV>
<div class="footerafterdiv">

</DIV>
<div class="globalafterdiv">

</DIV>
<div class="globalfooterdiv">

</DIV>
<div class="pagefooterdiv">
<SPAN class="releasetext">Release: 8.7.2.9</SPAN>
</DIV>
<div class="poweredbydiv">
</DIV>
<DIV class="div1"></DIV>
<DIV class="div2"></DIV>
<DIV class="div3"></DIV>
<DIV class="div4"></DIV>
<DIV class="div5"></DIV>
<DIV class="div6"></DIV>
<div class="banner_copyright"> <br><h5>© 2024 Ellucian Company L.P. and its affiliates.<br></h5></div>
</body>
"""
soup = BeautifulSoup(html_code, 'html.parser')

# Find all tables with class datadisplaytable
transcript_tables = soup.find_all('table', class_='datadisplaytable')

# Assuming the transcript details are in the first table (index 0)
transcript_table = transcript_tables[0]

# Extracting rows from the table
rows = transcript_table.find_all('tr')

# Loop through each row to extract data
transcript_data = []
for row in rows:
    # Extract cells from the row
    cells = row.find_all('td')
    row_data = [cell.get_text(strip=True) for cell in cells]
    transcript_data.append(row_data)
    term = row.find("span", class_="fieldOrangetextbold")
    #print(str(term))
    str_terms=str(term)
    if str_terms!=None:
        transcript_data.append(str_terms[34:52])
    

# Print the transcript details
import pandas as pd
transcript_results = pd.DataFrame(columns=['Course Code', 'Course Name', 'Grade', 'Credits', 'Semester'])
for row in transcript_data:
    if ("Term:" in row):
        current_term = row[6:len(row)]
    if ("CS" in row or "STAT" in row):
        if (len(row) == 9):
            new_row = pd.Series({'Course Code': row[0]+' '+row[1], 'Course Name': row[3], 
                                 'Grade': row[4], 'Credits': row[5], 'Semester': current_term})
            transcript_results = pd.concat([transcript_results, new_row.to_frame().T], ignore_index=True)
        elif (len(row) == 5):
            new_row = pd.Series({'Course Code': row[0]+' '+row[1], 'Course Name': row[3], 
                                 'Grade': ' ', 'Credits': row[4], 'Semester': current_term})
            transcript_results = pd.concat([transcript_results, new_row.to_frame().T], ignore_index=True)
            
print(transcript_results)
#print(transcript_results)
        #transcript_data.append(row)
    #print(row)
    #print(row)

  Course Code                     Course Name Grade Credits      Semester
0     CS 5610     Advanced R for Data Science     B   4.000  Spring 2023
1   STAT 5860    Computer Based Data Analysis    BA   3.000  Spring 2023
2   STAT 5630           Sample Survey Methods     A   3.000  SummerI 2023
3     CS 5430                Database Systems     B   3.000  Fall 2023
4   STAT 5870  Big Data Analysis Using Python     A   3.000  Fall 2023
5   STAT 6620           Applied Linear Models     B   3.000  Fall 2023
6     CS 5821                Machine Learning         3.000  Spring 2024
7   STAT 6640            Applied Mixed Models         3.000  Spring 2024

In [46]:
transcript_results

  Course Code                     Course Name Grade Credits      Semester
0     CS 5610     Advanced R for Data Science     B   4.000  Spring 2023
1   STAT 5860    Computer Based Data Analysis    BA   3.000  Spring 2023
2   STAT 5630           Sample Survey Methods     A   3.000  SummerI 2023
3     CS 5430                Database Systems     B   3.000  Fall 2023
4   STAT 5870  Big Data Analysis Using Python     A   3.000  Fall 2023
5   STAT 6620           Applied Linear Models     B   3.000  Fall 2023
6     CS 5821                Machine Learning         3.000  Spring 2024
7   STAT 6640            Applied Mixed Models         3.000  Spring 2024

In [47]:
import pandas as pd

# Output from your code snippet
output = [
    "Core:",
    "STAT 6620 - Applied Linear Models Credits: 3 hours",
    "STAT 5860 - Computer Based Data Analysis Credits: 3 hours",
    "STAT 5870 - Big Data Analysis Using Python Credits: 3 hours",
    "STAT 6800 - SAS Programming Credits: 3 hours",
    "CS 5430 - Database Systems Credits: 3 hours",
    "CS 5610 - Advanced R Programming for Data Science Credits: 4 hours",
    "CS 5821 - Machine Learning Credits: 3 hours",
    "CS 6100 - Advanced Storage, Retrieval and Processing of Big Data Credits: 3 hours",

    "Electives:",
    "STAT 6040 - Fundamentals of Epidemiology and Clinical Trials Credits: 3 hours",
    "STAT 6500 - Statistical Theory I Credits: 3 hours",
    "STAT 6600 - Statistical Theory II Credits: 3 hours",
    "STAT 6640 - Applied Mixed Models Credits: 3 hours",
    "CS 6030 - Studies in Computer Science Credits: 3 hours",
    "CS 6260 - Advanced Parallel Computations Credits: 3 hours",
    "CS 6310 - Advanced Design and Analysis of Algorithms Credits: 3 hours",
    "CS 6430 - Database Management System Implementation Credits: 3 hours",
    "CS 6530 - Data Mining Credits: 3 hours",
    "CS 6820 - Advanced Artificial Intelligence Credits: 3 hours",
    "CS 6821 - Information Retrieval Credits: 3 hours",

    "Masters Project:",
    "STAT 6970 - Data Science Masters Project Credits: 4 hours",
    "CS 6970 - Master’s Project Credits: 4 hours"
]

# Initialize a list to store course information dictionaries
course_info_list = []

# Initialize a variable to store the current category
current_category = None

# Extract course information and append it to the list
for line in output:
    # Check if the line indicates a category
    if line.endswith(":"):
        current_category = line.rstrip(":")
    else:
        # Split the line by spaces
        parts = line.split()
        # Extract course code
        course_code = parts[0] + " " + parts[1]
        # Find the index where 'Credits:' appears
        credits_index = parts.index('Credits:')
        # Extract course name
        course_name_parts = parts[2:credits_index]
        # Remove leading hyphen if present
        if course_name_parts[0] == '-':
            course_name_parts = course_name_parts[1:]
        course_name = ' '.join(course_name_parts)
        # Extract credits
        credits = ' '.join(parts[credits_index + 1:])
        # Append the extracted information as a dictionary to the list
        course_info_list.append({"Category": current_category, "Course Code": course_code.strip(), "Course Name": course_name.strip(), "Credits": credits.strip()})

# Create a DataFrame from the list of dictionaries
course_df = pd.DataFrame(course_info_list)

# Print the DataFrame
print(course_df)

           Category Course Code  \
0              Core   STAT 6620
1              Core   STAT 5860
2              Core   STAT 5870
3              Core   STAT 6800
4              Core     CS 5430
5              Core     CS 5610
6              Core     CS 5821
7              Core     CS 6100
8         Electives   STAT 6040
9         Electives   STAT 6500
10        Electives   STAT 6600
11        Electives   STAT 6640
12        Electives     CS 6030
13        Electives     CS 6260
14        Electives     CS 6310
15        Electives     CS 6430
16        Electives     CS 6530
17        Electives     CS 6820
18        Electives     CS 6821
19  Masters Project   STAT 6970
20  Masters Project     CS 6970

                                          Course Name  Credits
0                               Applied Linear Models  3 hours
1                        Computer Based Data Analysis  3 hours
2                      Big Data Analysis Using Python  3 hours
3                                     SAS Programming  3 hours
4                                    Database Systems  3 hours
5             Advanced R Programming for Data Science  4 hours
6                                    Machine Learning  3 hours
7   Advanced Storage, Retrieval and Processing of ...  3 hours
8    Fundamentals of Epidemiology and Clinical Trials  3 hours
9                                Statistical Theory I  3 hours
10                              Statistical Theory II  3 hours
11                               Applied Mixed Models  3 hours
12                        Studies in Computer Science  3 hours
13                     Advanced Parallel Computations  3 hours
14         Advanced Design and Analysis of Algorithms  3 hours
15          Database Management System Implementation  3 hours
16                                        Data Mining  3 hours
17                   Advanced Artificial Intelligence  3 hours
18                              Information Retrieval  3 hours
19                       Data Science Masters Project  4 hours
20                                   Master’s Project  4 hours

In [48]:
course_df

,Category,Course Code,Course Name,Credits
0,Core,STAT 6620,Applied Linear Models,3 hours
1,Core,STAT 5860,Computer Based Data Analysis,3 hours
2,Core,STAT 5870,Big Data Analysis Using Python,3 hours
3,Core,STAT 6800,SAS Programming,3 hours
4,Core,CS 5430,Database Systems,3 hours
5,Core,CS 5610,Advanced R Programming for Data Science,4 hours
6,Core,CS 5821,Machine Learning,3 hours
7,Core,CS 6100,"Advanced Storage, Retrieval and Processing of ...",3 hours
8,Electives,STAT 6040,Fundamentals of Epidemiology and Clinical Trials,3 hours
9,Electives,STAT 6500,Statistical Theory I,3 hours
10,Electives,STAT 6600,Statistical Theory II,3 hours
11,Electives,STAT 6640,Applied Mixed Models,3 hours
12,Electives,CS 6030,Studies in Computer Science,3 hours
13,Electives,CS 6260,Advanced Parallel Computations,3 hours
14,Electives,CS 6310,Advanced Design and Analysis of Algorithms,3 hours
15,Electives,CS 6430,Database Management System Implementation,3 hours
16,Electives,CS 6530,Data Mining,3 hours
17,Electives,CS 6820,Advanced Artificial Intelligence,3 hours
18,Electives,CS 6821,Information Retrieval,3 hours
19,Masters Project,STAT 6970,Data Science Masters Project,4 hours
20,Masters Project,CS 6970,Master’s Project,4 hours

In [50]:
# Merge course_df and transcript_df on "Course Code" using a left join
merge_df = pd.merge(course_df[['Course Code', 'Course Name', 'Category', 'Credits']], 
                    transcript_results[['Course Code', 'Grade', 'Semester']], 
                    on="Course Code", 
                    how="left")

# Print the merged dataframe
print(merge_df)

   Course Code                                        Course Name  \
0    STAT 6620                              Applied Linear Models
1    STAT 5860                       Computer Based Data Analysis
2    STAT 5870                     Big Data Analysis Using Python
3    STAT 6800                                    SAS Programming
4      CS 5430                                   Database Systems
5      CS 5610            Advanced R Programming for Data Science
6      CS 5821                                   Machine Learning
7      CS 6100  Advanced Storage, Retrieval and Processing of ...
8    STAT 6040   Fundamentals of Epidemiology and Clinical Trials
9    STAT 6500                               Statistical Theory I
10   STAT 6600                              Statistical Theory II
11   STAT 6640                               Applied Mixed Models
12     CS 6030                        Studies in Computer Science
13     CS 6260                     Advanced Parallel Computations
14     CS 6310         Advanced Design and Analysis of Algorithms
15     CS 6430          Database Management System Implementation
16     CS 6530                                        Data Mining
17     CS 6820                   Advanced Artificial Intelligence
18     CS 6821                              Information Retrieval
19   STAT 6970                       Data Science Masters Project
20     CS 6970                                   Master’s Project

           Category  Credits Grade      Semester
0              Core  3 hours     B  Fall 2023
1              Core  3 hours    BA  Spring 2023
2              Core  3 hours     A  Fall 2023
3              Core  3 hours   NaN           NaN
4              Core  3 hours     B  Fall 2023
5              Core  4 hours     B  Spring 2023
6              Core  3 hours        Spring 2024
7              Core  3 hours   NaN           NaN
8         Electives  3 hours   NaN           NaN
9         Electives  3 hours   NaN           NaN
10        Electives  3 hours   NaN           NaN
11        Electives  3 hours        Spring 2024
12        Electives  3 hours   NaN           NaN
13        Electives  3 hours   NaN           NaN
14        Electives  3 hours   NaN           NaN
15        Electives  3 hours   NaN           NaN
16        Electives  3 hours   NaN           NaN
17        Electives  3 hours   NaN           NaN
18        Electives  3 hours   NaN           NaN
19  Masters Project  4 hours   NaN           NaN
20  Masters Project  4 hours   NaN           NaN

In [51]:
merge_df

,Course Code,Course Name,Category,Credits,Grade,Semester
0,STAT 6620,Applied Linear Models,Core,3 hours,B,Fall 2023
1,STAT 5860,Computer Based Data Analysis,Core,3 hours,BA,Spring 2023
2,STAT 5870,Big Data Analysis Using Python,Core,3 hours,A,Fall 2023
3,STAT 6800,SAS Programming,Core,3 hours,NaN,NaN
4,CS 5430,Database Systems,Core,3 hours,B,Fall 2023
5,CS 5610,Advanced R Programming for Data Science,Core,4 hours,B,Spring 2023
6,CS 5821,Machine Learning,Core,3 hours,,Spring 2024
7,CS 6100,"Advanced Storage, Retrieval and Processing of ...",Core,3 hours,NaN,NaN
8,STAT 6040,Fundamentals of Epidemiology and Clinical Trials,Electives,3 hours,NaN,NaN
9,STAT 6500,Statistical Theory I,Electives,3 hours,NaN,NaN
10,STAT 6600,Statistical Theory II,Electives,3 hours,NaN,NaN
11,STAT 6640,Applied Mixed Models,Electives,3 hours,,Spring 2024
12,CS 6030,Studies in Computer Science,Electives,3 hours,NaN,NaN
13,CS 6260,Advanced Parallel Computations,Electives,3 hours,NaN,NaN
14,CS 6310,Advanced Design and Analysis of Algorithms,Electives,3 hours,NaN,NaN
15,CS 6430,Database Management System Implementation,Electives,3 hours,NaN,NaN
16,CS 6530,Data Mining,Electives,3 hours,NaN,NaN
17,CS 6820,Advanced Artificial Intelligence,Electives,3 hours,NaN,NaN
18,CS 6821,Information Retrieval,Electives,3 hours,NaN,NaN
19,STAT 6970,Data Science Masters Project,Masters Project,4 hours,NaN,NaN
20,CS 6970,Master’s Project,Masters Project,4 hours,NaN,NaN

In [52]:
merge_df=merge_df.fillna("")

In [53]:
merge_df

,Course Code,Course Name,Category,Credits,Grade,Semester
0,STAT 6620,Applied Linear Models,Core,3 hours,B,Fall 2023
1,STAT 5860,Computer Based Data Analysis,Core,3 hours,BA,Spring 2023
2,STAT 5870,Big Data Analysis Using Python,Core,3 hours,A,Fall 2023
3,STAT 6800,SAS Programming,Core,3 hours,,
4,CS 5430,Database Systems,Core,3 hours,B,Fall 2023
5,CS 5610,Advanced R Programming for Data Science,Core,4 hours,B,Spring 2023
6,CS 5821,Machine Learning,Core,3 hours,,Spring 2024
7,CS 6100,"Advanced Storage, Retrieval and Processing of ...",Core,3 hours,,
8,STAT 6040,Fundamentals of Epidemiology and Clinical Trials,Electives,3 hours,,
9,STAT 6500,Statistical Theory I,Electives,3 hours,,
10,STAT 6600,Statistical Theory II,Electives,3 hours,,
11,STAT 6640,Applied Mixed Models,Electives,3 hours,,Spring 2024
12,CS 6030,Studies in Computer Science,Electives,3 hours,,
13,CS 6260,Advanced Parallel Computations,Electives,3 hours,,
14,CS 6310,Advanced Design and Analysis of Algorithms,Electives,3 hours,,
15,CS 6430,Database Management System Implementation,Electives,3 hours,,
16,CS 6530,Data Mining,Electives,3 hours,,
17,CS 6820,Advanced Artificial Intelligence,Electives,3 hours,,
18,CS 6821,Information Retrieval,Electives,3 hours,,
19,STAT 6970,Data Science Masters Project,Masters Project,4 hours,,
20,CS 6970,Master’s Project,Masters Project,4 hours,,